version: '3'

services:
  backend:
    build: ./
    container_name: nestjs_api2
    environment:
      - RABBIT_MQ=amqp://107.21.134.141:5672

    depends_on:
      - rabbitmq
    networks:
      - nestjs_network

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/data'

volumes:
  rabbitmq_data:
networks:
  nestjs_network:
    driver: bridge
